- name: Create Container Lab environment
  hosts: lab
  gather_facts: false
  vars:
    templates_path: "{{ playbook_dir }}/../templates"
    project_path: "{{ playbook_dir }}/../labs/{{ project_name }}"
  tasks:
    - name: Create lab directory
      ansible.builtin.file:
        path: "{{ project_path }}"
        state: directory

    - name: Create templated_nodes variable
      ansible.builtin.include_tasks:
        file: tasks/create_templated_nodes_var.yaml

    - name: Create topology file
      vars:
        topology_nodes: |
          {% set nodes = {} %}
          {% for node, node_values in topology.nodes.items() | default({}) %}
          {% if node_values.kind != 'templated' %}
          {% set _ = nodes.update({node: node_values}) %}
          {% endif %}
          {% endfor %}
          {{ nodes }}
      ansible.builtin.template:
        src: "{{ templates_path }}/topology.clab.yaml.j2"
        dest: "{{ project_path }}/topology.clab.yaml"
